# Generated by Django 4.2.3 on 2023-07-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_profile_options_alter_post_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('about', models.TextField()),
            ],
        ),
    ]
