# Generated by Django 4.2.3 on 2023-07-30 22:42

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_websitemeta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitemeta',
            options={'verbose_name': 'website metas', 'verbose_name_plural': 'website metas'},
        ),
        migrations.AddField(
            model_name='profile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='websitemeta',
            name='about',
            field=ckeditor.fields.RichTextField(verbose_name='About'),
        ),
    ]
